categories:
  In2studyfinder:
    label: 'In2studyfinder'
  In2studyfinder.templates:
    label: 'Templates'
    parent: In2studyfinder

settings:
  plugin.tx_in2studyfinder.view.templateRootPath:
    label: 'Template root path'
    category: In2studyfinder.templates
    description: 'Path to template root'
    type: string
    default: EXT:in2studyfinder/Resources/Private/Templates/
  plugin.tx_in2studyfinder.view.partialRootPath:
    label: 'Partial root path'
    category: In2studyfinder.templates
    description: 'Path to partial root'
    type: string
    default: EXT:in2studyfinder/Resources/Private/Partials/
  plugin.tx_in2studyfinder.view.layoutRootPath:
    label: 'Layout root path'
    category: In2studyfinder.templates
    description: 'Path to layout root'
    type: string
    default: EXT:in2studyfinder/Resources/Private/Layouts/
