categories:
  In2studyfinder:
    label: 'In2studyfinder'
  In2studyfinder.templates:
    label: 'Templates'
    parent: In2studyfinder

settings:
  in2studyfinder.templateRootPath:
    label: 'Template root path'
    category: In2studyfinder.templates
    description: 'Path to template root'
    type: string
    default: EXT:in2studyfinder/Resources/Private/Templates/
  in2studyfinder.partialRootPath:
    label: 'Partial root path'
    category: In2studyfinder.templates
    description: 'Path to partial root'
    type: string
    default: EXT:in2studyfinder/Resources/Private/Partials/
  in2studyfinder.layoutRootPath:
    label: 'Layout root path'
    category: In2studyfinder.templates
    description: 'Path to layout root'
    type: string
    default: EXT:in2studyfinder/Resources/Private/Layouts/
