<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "in2studyfinder"
 *
 * Auto generated by Extension Builder 2016-04-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'in2studyfinder',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Sebastian Stein',
    'author_email' => 'sebastian.stein@in2code.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.3.0-dev',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-7.6.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);
