#!/bin/bash

# This is a git pre-commit hook that prevents a commit from being created if the code style isn't proper

# first we get everything we need to check, which are the staged changes
CHANGES=$(git diff --name-status --cached)

# if the changelist contains .php files, run php-cs-fixer in the PHP container
if echo "$CHANGES" | grep -q -E "^[AMCR].+(\.php)$"; then
    echo "Running PHP QA checks..."
    ddev qa-php

    if [[ $? -ne 0 ]]; then
        exit 1
    fi
fi
