version: '3.6'
services:
  web:
    environment:
      - TYPO3_CONTEXT=Development/DDEV
      - TYPO3_PATH_APP=/var/www/html/.build
      - MYSQL_DATABASE=db
      - MYSQL_PASSWORD=db
      - MYSQL_USER=db
      - MYSQL_HOST=db
      - MAIL_HOST=localhost:1025
      - typo3DatabaseName=testing
      - typo3DatabaseHost=db
      - typo3DatabaseUsername=root
      - typo3DatabasePassword=root
      - typo3DatabasePort=3306
